### ISSUE TITLE
PIL.Image install

### ISSUE THREAD

**Issue by picaosgeo** [eachiaradia/IOGeopaparazzi#1]
Hi enrico,

Add comment to README.md and metadata.txt about "PIL.Image installation".

http://pillow.readthedocs.io/en/latest/installation.html

Default installation both of  QGIS and osgeo4w do not install PIL.Image
So, plug-in users should need to install Pillow library before install "IO Geopaparazzi".

Regards,
Hayashi

**Comment by eachiaradia** [comment]
Hi Hayashi,
I swear I tested the plugin on a clean linux machine (ubuntu + QGIS 2.14) before publish it and I had no warnings about PIL! As it is not required, I deleted all the reference to it in the last version (0.1.2). Sorry for that.
enrico

**Comment by eachiaradia** [comment]
I think I can close this issue as it was resolved with the 0.1.2 release.
