### ISSUE TITLE
Please remove the binary file

### ISSUE THREAD

**Issue by pcav** [eachiaradia/IOGeopaparazzi#3]
Thanks.

**Comment by eachiaradia** [comment]
I think it was referred to the .gpap file. I removed it from the repository.

**Comment by pcav** [comment]
Right:
https://github.com/eachiaradia/IOGeopaparazzi/blob/master/sample/test1.gpap
Please publish a new version, and remove those containing the binary.
Thanks a lot.

**Comment by eachiaradia** [comment]
I removed all binaries from the repository (and also some heavy gifs for the wiki ..) so the repository is consistent with what was loaded on the qgis repository. Finally, I made some improvements to make the plugin more usable.
cheers
enrico
