### ISSUE TITLE
Output mbtiles file cannot be read in by QGIS

### ISSUE THREAD

**Issue by isaacullah** [eachiaradia/IOGeopaparazzi#4]
Hi, I am able to use your very nice plugin to seemingly successfully export an mbtiles file from a map. I believe I set everything correctly. I set the canvas extent, minimum zoom to 10.000, maximum zoom to 18.000, and gave a correct output name. It processes, and after awhile made the mbtiles file with more than 3000 tiles. The created file is 206 megabytes, which seems correct. However, when I go to load it into QGIS to check it (as your video on the Github Readme shows you do), I get the following error:
`Unsupported Data Source: /home/iullah/SP_Proj_area.mbtiles is not a supported raster data source Cannot find min and max zoom_level`
I have also tried to load it into GeoODk (the mapping tool I use on my tablet instead of Geopap) to see if it works (after correction with the Qtiles Tools plugin). The file is accepted, but nothing loads. So it seems like it is a problem in the file itself, and somehow there is no information about the zoom level. I am using QGIS 2.18.9 on Ubuntu 16.04. The original map was a geotiff raster file in WGS84 LatLon projection.

**Comment by eachiaradia** [comment]
Hi, it seem like that the file was not completely generated. That could explain the absence of the zoom levels. Did you test any other files? Could you test a smaller area dimension to make the process faster?

**Comment by eachiaradia** [comment]
I just realized that the current version of the plugin doesn't accept a minimum zoom level lower than 16 (That is a bug, I will fix it as soon as possible!!!!). How did you set 10 instead?

**Comment by isaacullah** [comment]
Thanks for the very fast reply! When I loaded the plugin, the minimum zoom level was set to 10 by default, and i did not change it. I did try a couple of different files, with no success. I will try again with a smaller area and with minimum zoom set to 16, and report back.

**Comment by isaacullah** [comment]
Darn. It still doesn't work. I tried several other maps as well including a dead standard SRTM geoiff downloaded from earthexplorer.gov. I also tried reprojecting into the EPSG:3857 (standard web mercator) CRS. I even set *both* minimum and maximum zoom to 18.  I'm also on a different computer now that also has Ubuntu 16.04 and QGIS 2.18.9. It still gives the same error every time I try to load in the exported mbtiles file. Anything else I can try? Any other info you might need to help debug?

**Comment by eachiaradia** [comment]
I made a test using a geotiff from USGS (n43_w112_1arc_v3) under QGIS 2.14.14 and Win10.
Setting the output extension to -111.362172152,-111.29230701,43.4957330805,43.5507947557, minimum and maximum zoom respectively to 16 and 18 (the default) and tile dimension to 256, it creates 3913 tiles and the final file can be correctly loaded into QGIS. So, the plugin works perfectly for me and unfortunately I cannot reproduce the issue.
If you provide the name of the layer to use, the output extension and the tile dimension I can try to reproduce the error on my system. Otherwise, it's hard to understand the cause of the problem.

**Comment by isaacullah** [comment]
Thanks for checking Enrico. I was able to successfully make mbtiles files from these same layers with the the QMetaTiles plugin, so in a sense "my" issue is resolved (I needed to get these files made). But I can still not make it work with your plugin, so the "actual" problem seems to still exist. So that you can try to exactly replicate what I have done, I am using a USGS SRTM DEM geotiff, n38_e015_1arc_v3.tif. I select area 15.6650613978,15.7511330178,38.1568030342,38.2581278527, and leave all settings to default (minimum zoom 16, max zoom 18, tile size 256). The module runs, making 8024 tiles, and output mbtiles file of 19.5MB. I try to load in, and I get the same error.
  I note that there are two differences between your installation and mine. The first difference is that while you are using the LTS version of QGIS (2.14.14), I am using the latest stable 2.18.9. The second difference is that you are using Windows 10, and I am using Ubuntu Linux 16.04. I have had the same error on two separate computers, both using QGIS 2.18.9 and with Ubuntu 16.04, which suggest to me that it might be either an incompatibility of the plugin in with the latest QGIS (less likely, I think), or with Ubuntu (and perhaps Linux more generally). That second seems perhaps more likely, as there may be some formatting or permissions issues on Linux that differ from Windows. I develop addon modules for GRASS GIS, and I often come across such incompatibilities. One common one is that Windows and Linux use different line endings and path structures, and you have to put some OS checks in your code to write the proper line endings and paths in temporary text files, etc. I don't know that that is the issue here, but something perhaps to start with? 
Again, let me know what else you might need from me, and I will be glad to help as much as I can! :)
~Isaac Ullah 

    On Monday, June 5, 2017 5:53 AM, Enrico A. Chiaradia <notifications@github.com> wrote:
 

 I made a test using a geotiff from USGS (n43_w112_1arc_v3) under QGIS 2.14.14 and Win10.
Setting the output extension to -111.362172152,-111.29230701,43.4957330805,43.5507947557, minimum and maximum zoom respectively to 16 and 18 (the default) and tile dimension to 256, it creates 3913 tiles and the final file can be correctly loaded into QGIS. So, the plugin works perfectly for me and unfortunately I cannot reproduce the issue.
If you provide the name of the layer to use, the output extension and the tile dimension I can try to reproduce the error on my system. Otherwise, it's hard to understand the cause of the problem.—

**Comment by eachiaradia** [comment]
I confirm that under QGIS 2.14.14 - Win10 the plugin works as aspected also with your settings. I will check it also under linux as soon as possible.

**Comment by eachiaradia** [comment]
Please, download the latest source from GitHub for testing.
