### ISSUE TITLE
Where can I find the plugin?

### ISSUE THREAD

**Issue by crilose** [eachiaradia/IOGeopaparazzi#6]
Hello.
I've correctly installed the plugin directly by the qGIS interface but I can't seem to find out where the option to use it is. 
Is there an icon or a submenu anywhere? I really need the plugin for some school work and I'd like to find out how to use it.
Thank you already.

**Comment by eachiaradia** [comment]
Hi,
you should find all the functions under the processing framework.
Go to Processing (menu) --> toolbox and look for "Import/export from/to Geopaparazzi" in the toolbox frame.
If you cannot see Processing, maybe you have to activate it from the Plugins (menu) --> Manage and install plugins.
If you cannot find "Import/export from/to Geopaparazzi" in the toolbox frame, maybe you have to load it in the processing framework. Go under Processing (menu) --> Options --> Providers and look for "Import/export from/to Geopaparazzi" and then activate it.
Let me know if you resolve your problem.
Cheers.

**Comment by crilose** [comment]
Hello,
Thank you for the answer and yes it actually was easy to find.
Sorry for the useless issue.
