### ISSUE TITLE
QGIS 3 ;  is IOGeopaparazzi available

### ISSUE THREAD

**Issue by GeoHigh125** [eachiaradia/IOGeopaparazzi#8]
Do you  know or the plugin is working within QGIS3 ?

**Comment by eachiaradia** [comment]
I have not tested it yet but I scheduled to verify it in the next days.

**Comment by AndrewM-** [comment]
Please let us know when it has been released and we can try it out and get back to you if there are any issues.

**Comment by eachiaradia** [comment]
Dear all,
I'm working on the porting project of  IOGeopaparazzi to QGIS3 and I realised that I have to modify some behaviours of the plugin to comply with the new processing framework that seems not to support some functions required by my plugin. Also, I'd like to take advantage of the new functionalities of QGSI3. So, be patient and I will produce a new powerfull version of the plugin as soon as possible!

**Comment by AndrewM-** [comment]
It is the ability to import gpap data into geopackages that is the most important.  All the making of tiled images etc can wait.  We can always use QGIS V2 to create mbtiles but importing gpap data is much more frequent and would be nice to have in Q3.  Unfortunately it is beyond me to port the code as there are additional considerations as you have suggested.

**Comment by eachiaradia** [comment]
I have update the current master release to run exclusively under QGIS 3.x. Import gpap function is already implemented so you can test and use it if you want. Note that is a very early version!

**Comment by AndrewM-** [comment]
Thank you.  I have downloaded the repo as a zip file then installed the plug-in from the zip file in QGIS 3.2.2.  There were no problems.  Then I imported the biggest fatest gpap file I have which contains tracks, photos, forms etc and it all worked well.

**Comment by eachiaradia** [comment]
Please, download the latest source from GitHub for testing.
